remote_theme: irukabando/pafe
url: https://irukabando.github.io/AquariumMatching
name: 水族館マッチング
icon: /images/irukabando_icon.jpg
head: /images/irukabando_icon.jpg
lead: &desc 利用者の興味にマッチした水族館を提案します。
desc: *desc
items:
- name: マッチング
  href: /AquariumMatching/matching.html
  icon: fas fa-fish
- name: コンテンツ
  href: /AquariumMatching/contents
  icon: fas fa-book
links:
- name:
  href: https://github.com/irukabando/AquariumMatching
  icon: fas fa-edit
- name: X
  href: https://x.com/sendaiperson
jumps:
- name: マッチング
  href: /AquariumMatching/matching.html
  icon: fas fa-fish
- name: コンテンツ
  href: /AquariumMatching/contents
  icon: fas fa-book
nomath: true
plugins:
- jekyll-sitemap
