remote_theme: autodyne/pafe
name: 水族館マッチング
lead: 
desc: 
items:
- name: マニュアル
  href: /manual
  icon: fas fa-book
- name: プラグイン
  href: /plugins.html
  icon: fas fa-shopping-cart
- name: ダウンロード
  href: /downloads.html
  icon: fas fa-download
links:
- name:
  href: https://github.com/nextzlog/use.zlog.org
  icon: fas fa-edit
jumps:
- name: マニュアル
  href: /manual
  icon: fas fa-book
- name: ダウンロード
  href: /downloads
  icon: fas fa-download
- name: アンケート
  href: /survey
  icon: fas fa-poll
nomath: true
plugins:
- jekyll-sitemap
